resolver: lts-7.1
packages:
- '.'
- '../data-bitcode'
- '../data-bitcode-llvm'
- '../data-bitcode-edsl'

extra-deps: []
flags: {}
extra-package-dbs: []
ghc-options: 
  "*": -fllvm
system-ghc: true
compiler: ghc-8.0.1
